database:
  host: localhost
  port: 3306
  username: root
  password: root
  dbname: test
  charset: utf8mb4
  max_idle_conns: 10 # 空闲连接池中连接的最大数量
  max_open_conns: 100 # 打开数据库连接的最大数量

app:
  name: ebss_golang
  port: 8054